echo "\x1B[32mTest nm:\x1B[0m"
echo "../libft/libft.a"
./nm_test.sh ../libft/libft.a
echo "../libft/ft_atoi.o"
./nm_test.sh ../libft/ft_atoi.o
echo "/usr/share/examshell/venv/lib/python2.7/site-packages/_cffi_backend.so"
./nm_test.sh /usr/share/examshell/venv/lib/python2.7/site-packages/_cffi_backend.so
echo "./test_files/libft_malloc_x86_64_Darwin.so"
./nm_test.sh ./test_files/libft_malloc_x86_64_Darwin.so
echo "/usr/lib/pam/pam_deny.so.2"
./nm_test.sh /usr/lib/pam/pam_deny.so.2
echo "/usr/lib/libgmalloc.dylib"
./nm_test.sh /usr/lib/libgmalloc.dylib
echo "/usr/lib/dtrace/libdtrace_dyld.dylib"
./nm_test.sh /usr/lib/dtrace/libdtrace_dyld.dylib
echo "/usr/lib/libAccountPolicyTranslation.dylib"
./nm_test.sh /usr/lib/libAccountPolicyTranslation.dylib
echo "/usr/lib/libgmalloc.dylib"
./nm_test.sh /usr/lib/libgmalloc.dylib
echo "./test_files/bin_32"
./nm_test.sh ./test_files/bin_32
echo "./test_files/ft_nm32"
./nm_test.sh ./test_files/ft_nm32
echo "./test_files/main32"
./nm_test.sh ./test_files/main32
echo "/bin/launchctl"
./nm_test.sh /bin/launchctl
echo "/bin/echo"
./nm_test.sh /bin/echo
echo "/sbin/ifconfig"
./nm_test.sh /sbin/ifconfig
echo "/sbin/mount_smbfs"
./nm_test.sh /sbin/mount_smbfs
echo "/usr/bin/python2.6"
./nm_test.sh /usr/bin/python2.6
echo "/usr/bin/dc"
./nm_test.sh /usr/bin/dc
echo "/usr/sbin/traceroute"
./nm_test.sh /usr/sbin/traceroute
echo "/usr/bin/ditto"
./nm_test.sh /usr/bin/ditto
echo "/usr/bin/sips"
./nm_test.sh /usr/bin/sips
echo "/usr/sbin/ktutil"
./nm_test.sh /usr/sbin/ktutil
echo "/usr/sbin/dsconfigldap"
./nm_test.sh /usr/sbin/dsconfigldap
echo "../libft/libft.a ../libft/ft_atoi.o ./test_files/libft_malloc_x86_64_Darwin.so /usr/lib/libgmalloc.dylib ./test_files/main32 /bin/launchctl /sbin/mount_smbfs /usr/sbin/traceroute /usr/sbin/dsconfigldap"
./nm_test.sh ../libft/libft.a ../libft/ft_atoi.o ./test_files/libft_malloc_x86_64_Darwin.so /usr/lib/libgmalloc.dylib ./test_files/main32 /bin/launchctl /sbin/mount_smbfs /usr/sbin/traceroute /usr/sbin/dsconfigldap
echo ""
echo "\x1B[32mTest otool:\x1B[0m"
echo "../libft/libft.a"
./otool_test.sh ../libft/libft.a
echo "../libft/ft_atoi.o"
./otool_test.sh ../libft/ft_atoi.o
echo "/usr/share/examshell/venv/lib/python2.7/site-packages/_cffi_backend.so"
./otool_test.sh /usr/share/examshell/venv/lib/python2.7/site-packages/_cffi_backend.so
echo "./test_files/libft_malloc_x86_64_Darwin.so"
./otool_test.sh ./test_files/libft_malloc_x86_64_Darwin.so
echo "/usr/lib/libgmalloc.dylib"
./otool_test.sh /usr/lib/libgmalloc.dylib
echo "./test_files/bin_32"
./otool_test.sh ./test_files/bin_32
echo "./test_files/ft_nm32"
./otool_test.sh ./test_files/ft_nm32
echo "./test_files/main32"
./otool_test.sh ./test_files/main32
echo "/bin/launchctl"
./otool_test.sh /bin/launchctl
echo "/bin/echo"
./otool_test.sh /bin/echo
echo "/sbin/ifconfig"
./otool_test.sh /sbin/ifconfig
echo "/sbin/mount_smbfs"
./otool_test.sh /sbin/mount_smbfs
echo "/usr/bin/python2.6"
./otool_test.sh /usr/bin/python2.6
echo "/usr/bin/dc"
./otool_test.sh /usr/bin/dc
echo "/usr/sbin/traceroute"
./otool_test.sh /usr/sbin/traceroute
echo "/usr/lib/pam/pam_deny.so.2"
./otool_test.sh /usr/lib/pam/pam_deny.so.2
echo "/usr/lib/libgmalloc.dylib"
./otool_test.sh /usr/lib/libgmalloc.dylib
echo "/usr/lib/dtrace/libdtrace_dyld.dylib"
./otool_test.sh /usr/lib/dtrace/libdtrace_dyld.dylib
echo "/usr/lib/libAccountPolicyTranslation.dylib"
./otool_test.sh /usr/lib/libAccountPolicyTranslation.dylib
echo "/usr/bin/ditto"
./otool_test.sh /usr/bin/ditto
echo "/usr/bin/sips"
./otool_test.sh /usr/bin/sips
echo "/usr/sbin/ktutil"
./otool_test.sh /usr/sbin/ktutil
echo "/usr/sbin/dsconfigldap"
./otool_test.sh /usr/sbin/dsconfigldap
echo "../libft/libft.a ../libft/ft_atoi.o ./test_files/libft_malloc_x86_64_Darwin.so /usr/lib/libgmalloc.dylib ./test_files/main32 /bin/launchctl /sbin/mount_smbfs /usr/sbin/traceroute /usr/sbin/dsconfigldap"
./otool_test.sh ../libft/libft.a ../libft/ft_atoi.o ./test_files/libft_malloc_x86_64_Darwin.so /usr/lib/libgmalloc.dylib ./test_files/main32 /bin/launchctl /sbin/mount_smbfs /usr/sbin/traceroute /usr/sbin/dsconfigldap
